\import Algebra.Group
\import Algebra.Group.GroupCat
\import Algebra.Group.GroupHom
\import Arith.Int
\import Category \hiding (id, o)
\import Equiv
\import Function
\import Homotopy.HomotopyGroup
\import Homotopy.Loop
\import Homotopy.Pointed
\import Homotopy.Sphere
\import Homotopy.Sphere.Circle
\import Logic
\import Paths
\import Set \hiding (#, .#)

\func PiGroup_S1.{u} : PiGroup 0 (Sphere.pointed 1) = {Group.{u}} AddGroup.toGroup IntRing
  => inv (Cat.isotoid iso)
  \where {
    \func windHom : GroupHom (AddGroup.toGroup IntRing) (PiGroup 0 (Pointed.make base1)) \cowith
      | func z => in0 (wind z)
      | func-* {x} {y} => pmap in0 (wind-+ x y)

    \func windEquiv : QEquiv {Int} {pi 1 (Pointed.make base1)}
      => symQEquiv (transQEquiv (Trunc0.mapEquiv Loop_S1-equiv) Trunc0.setEquiv)

    \func circleMap : Pointed.make base1 ->* Sphere.pointed 1
      => (Sphere1-equiv.f, idp)

    \func circleEquiv : QEquiv (piMap 1 circleMap)
      => IsEquiv.toQEquiv (piMap-isEquiv 1 circleMap (inP Sphere1-equiv))

    \func hom : GroupHom (AddGroup.toGroup IntRing) (PiGroup 0 (Sphere.pointed 1))
      => GroupHom.compose (piGroupMap 0 circleMap) windHom

    \func iso : Iso {GroupCat} hom
      => (GroupCat.Iso<->Inj+Surj hom).2
          (IsInj.comp windEquiv.isInj circleEquiv.isInj,
           IsSurj.comp windEquiv.isSurj circleEquiv.isSurj)
  }
