\import Algebra.Group
\import Algebra.Group.GroupCat
\import Algebra.Group.GroupHom
\import Algebra.Group.Product
\import Arith.Int
\import Category \hiding (id, o)
\import Equiv
\import Equiv.Sigma
\import Homotopy.HomotopyGroup
\import Homotopy.HomotopyGroup.Circle
\import Homotopy.Pointed
\import Homotopy.Sphere
\import Homotopy.Sphere.Circle
\import Homotopy.Torus
\import Logic
\import Paths

\func PiGroup_Torus.{u}
  : PiGroup 0 (Pointed.make point) = {Group.{u}} ProductGroup (AddGroup.toGroup IntRing) (AddGroup.toGroup IntRing)
  => Cat.isotoid iso.{u}
     *> PiGroup_Product.{u} 0 (Sphere.pointed 1) (Sphere.pointed 1)
     *> pmap2 (\lam (G H : Group.{u}) => ProductGroup G H) PiGroup_S1.{u} PiGroup_S1.{u}
  \where {
    \func torusEquiv : QEquiv {Torus} {\Sigma (Sphere 1) (Sphere 1)}
      => transQEquiv TorusSphere-equiv (sigma-equiv Sphere1-equiv (\lam _ => Sphere1-equiv))

    \func torusMap : Pointed.make point ->* PointedProduct (Sphere.pointed 1) (Sphere.pointed 1)
      => (torusEquiv, idp)

    \func hom
      : GroupHom (PiGroup 0 (Pointed.make point)) (PiGroup 0 (PointedProduct (Sphere.pointed 1) (Sphere.pointed 1)))
      => piGroupMap 0 torusMap

    \func iso.{u} : Iso {GroupCat.{u}} hom
      => GroupCat.isoOfEquiv hom (IsEquiv.toQEquiv (piMap-isEquiv 1 torusMap (inP torusEquiv)))
  }
