\import Algebra.Group
\import Algebra.Group.GroupHom
\import Algebra.Group.Pairing
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.MonoidHom
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.FormalSeries
\import Algebra.Ring.RingHom
\import Arith.Nat
\import Data.Or
\import Equiv
\import Logic
\import Logic.Meta
\import Meta
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set
\import Set.Fin.Instances

\open FSeriesRing (PairsFinSet)

\func sum-below {G : AddMonoid} (f : Nat -> G) (N : Nat) : G \elim N
  | 0 => 0
  | suc N => sum-below f N + f N
  \where {
    \lemma zero {G : AddMonoid} {f : Nat -> G} {N : Nat} (z : \Pi (n : Nat) -> n < N -> f n = 0) : sum-below f N = 0 \elim N
      | 0 => idp
      | suc N => pmap2 (+) (zero \lam n n<N => z n (n<N <∘ id<suc)) (z N id<suc) *> zro-left

    \lemma pad {G : AddMonoid} {f : Nat -> G} {N : Nat} (z : \Pi (n : Nat) -> N <= n -> f n = 0) (k : Nat) : sum-below f (N Nat.+ k) = sum-below f N \elim k
      | 0 => idp
      | suc k => pmap2 (+) (pad z k) (z (N Nat.+ k) (NatSemiring.<=_+ <=-refl zero<=_)) *> zro-right

    \lemma bounds {G : AddMonoid} {f : Nat -> G} {N M : Nat} (zN : \Pi (n : Nat) -> N <= n -> f n = 0) (zM : \Pi (n : Nat) -> M <= n -> f n = 0)
      : sum-below f N = sum-below f M
      => inv (pad zN M) *> pmap (sum-below f) NatSemiring.+-comm *> pad zM N

    \lemma hom {G H : AddMonoid} (h : AddMonoidHom G H) (f : Nat -> G) (N : Nat) : h (sum-below f N) = sum-below (\lam n => h (f n)) N \elim N
      | 0 => h.func-zro
      | suc N => h.func-+ *> pmap (`+ _) (hom h f N)

    \lemma add {G : AbMonoid} (f g : Nat -> G) (N : Nat) : sum-below (\lam n => f n + g n) N = sum-below f N + sum-below g N \elim N
      | 0 => inv zro-left
      | suc N => pmap (`+ _) (add f g N) *> equation

    \lemma unique {G : AddMonoid} {f : Nat -> G} {N n : Nat} (n<N : n < N) (z : \Pi (k : Nat) -> k /= n -> f k = 0) : sum-below f N = f n \elim N
      | suc N => \case decideEq n N \with {
        | yes e => pmap (`+ _) (zero \lam k k<N => z k \lam p => absurd linarith) *> zro-left *> pmap f (inv e)
        | no ne => pmap2 (+) (unique (LinearOrder.<=_/= (<_suc_<= n<N) ne) z) (z N (\lam p => ne (inv p))) *> zro-right
      }
  }

\func signed {G : AddGroup} (k : Nat) (a : G) : G \elim k
  | 0 => a
  | 1 => negative a
  | suc (suc k) => signed k a
  \where {
    \lemma twice {G : AddGroup} (k : Nat) (a : G) : signed k (signed k a) = a \elim k
      | 0 => idp
      | 1 => AddGroup.negative-isInv
      | suc (suc k) => twice k a

    \lemma hom {G H : AddGroup} (f : AddGroupHom G H) (k : Nat) (a : G) : f (signed k a) = signed k (f a) \elim k
      | 0 => idp
      | 1 => f.func-negative
      | suc (suc k) => hom f k a
  }

\record GradedProduct (H : Nat -> AbGroup) {
  | mul (p q : Nat) : Pairing (H p) (H q) (H (p Nat.+ q))
  | one : H 0
  | mul-assoc (p q r : Nat) (a : H p) (b : H q) (c : H r)
    : mul (p Nat.+ q) r (mul p q a b) c = transport (\lam n => H n) (inv NatSemiring.+-assoc) (mul p (q Nat.+ r) a (mul q r b c))
  | ide-left (q : Nat) (b : H q) : mul 0 q one b = b
  | ide-right (p : Nat) (a : H p) : mul p 0 a one = a

  \func cast {n m : Nat} (e : n = m) : AddGroupHom (H n) (H m) \cowith
    | func => transport (\lam k => H k) e
    | func-+ => cast-+ e

  \lemma cast-+ {n m : Nat} (e : n = m) {a b : H n} : transport (\lam k => H k) e (a + b) = transport (\lam k => H k) e a + transport (\lam k => H k) e b \elim m, e
    | _, idp => idp

  \lemma cast-comp {n m k : Nat} (e : n = m) (e' : m = k) (c : H n) : cast e' (cast e c) = cast (e *> e') c \elim k, e'
    | _, idp => idp

  \lemma cast-unique {n m : Nat} (e e' : n = m) (c : H n) : cast e c = cast e' c
    => pmap (\lam e'' => cast e'' c) prop-pi

  \lemma cast-left {p p' : Nat} (e : p = p') (q : Nat) (a : H p) (b : H q)
    : mul p' q (cast e a) b = cast (pmap (Nat.`+ q) e) (mul p q a b) \elim p', e
    | _, idp => idp
}

\record GradedCommProduct \extends GradedProduct
  | koszul (p q : Nat) (a : H p) (b : H q) : mul p q a b = signed (q Nat.* p) (cast NatSemiring.+-comm (mul q p b a))

\func DirectSum (D : GradedProduct) : Ring \cowith
  | E => \Sigma (x : \Pi (n : Nat) -> D.H n) (∃ (N : Nat) (\Pi (n : Nat) -> N <= n -> x n = 0))
  | zro => (\lam _ => 0, inP (0, \lam _ _ => idp))
  | + x y => (\lam n => x.1 n + y.1 n, \case x.2, y.2 \with {
    | inP (N, f), inP (M, g) => inP (N Nat.+ M, \lam n le => pmap2 (+) (f n (left-le le)) (g n (right-le le)) *> zro-left)
  })
  | zro-left => sum-ext \lam n => zro-left
  | +-assoc => sum-ext \lam n => +-assoc
  | +-comm => sum-ext \lam n => +-comm
  | negative x => (\lam n => negative (x.1 n), \case x.2 \with {
    | inP (N, f) => inP (N, \lam n le => pmap negative (f n le) *> AddGroup.negative_zro)
  })
  | negative-left => sum-ext \lam n => negative-left
  | ide => (unit D, inP (1, \lam n le => unit-suc D (\lam p => absurd linarith)))
  | * x y => (\lam n => conv D x.1 y.1 n, \case x.2, y.2 \with {
    | inP (N, f), inP (M, g) => inP (N Nat.+ M, \lam n le => AbMonoid.FinSum_zro {D.H n} {PairsFinSet n} \lam s => \case LinearOrder.dec<_<= s.1 N \with {
      | inl s1<N => conv-zero-right D x.1 y.1 s (g s.2 (support-le le s.3 s1<N))
      | inr N<=s1 => conv-zero-left D x.1 y.1 s (f s.1 N<=s1)
    })
  })
  | ide-left {x} => sum-ext \lam n => AbMonoid.FinSum-unique {D.H n} {PairsFinSet n} (0, n, idp)
      (\lam s s/=0 => conv-zero-left D (unit D) x.1 s (unit-suc D \lam p => s/=0 (ext (p, pmap (Nat.`+ s.2) (inv p) *> s.3)))) *> D.cast-unique _ idp _ *> D.ide-left n (x.1 n)
  | ide-right {x} => sum-ext \lam n => AbMonoid.FinSum-unique {D.H n} {PairsFinSet n} (n, 0, idp)
      (\lam s s/=0 => conv-zero-right D x.1 (unit D) s (unit-suc D \lam p => s/=0 (ext (pmap (s.1 Nat.+) (inv p) *> s.3, p)))) *> D.cast-unique _ idp _ *> D.ide-right n (x.1 n)
  | *-assoc {x} {y} {z} => sum-ext \lam n => conv-assoc D x.1 y.1 z.1 n
  | ldistr => sum-ext \lam n => AbMonoid.FinSum-ext {D.H n} {PairsFinSet n}
                                  (\lam s => pmap (D.cast s.3) (Pairing.ldistr {D.mul s.1 s.2}) *> AddGroupHom.func-+ {D.cast s.3})
                                *> AbMonoid.FinSum_+
  | rdistr => sum-ext \lam n => AbMonoid.FinSum-ext {D.H n} {PairsFinSet n}
                                  (\lam s => pmap (D.cast s.3) (Pairing.rdistr {D.mul s.1 s.2}) *> AddGroupHom.func-+ {D.cast s.3})
                                *> AbMonoid.FinSum_+
  \where {
    \func inc (D : GradedProduct) (n : Nat) : AddGroupHom (D.H n) (DirectSum D) \cowith
      | func a => (\lam k => inc-at D n a k, inP (suc n, \lam k le => inc-at-other D a (\lam p => absurd linarith)))
      | func-+ {a} {b} => sum-ext \lam k => \case decideEq n k \with {
        | yes e => inc-at-same D _ e *> D.cast-+ e *> inv (pmap2 (+) (inc-at-same D a e) (inc-at-same D b e))
        | no ne => inc-at-other D _ ne *> inv (pmap2 (+) (inc-at-other D a ne) (inc-at-other D b ne) *> zro-left)
      }

    \func proj (D : GradedProduct) (n : Nat) : AddGroupHom (DirectSum D) (D.H n) \cowith
      | func x => x.1 n
      | func-+ => idp

    \func inc-at (D : GradedProduct) (n : Nat) (a : D.H n) (k : Nat) : D.H k
      => \case decideEq n k \with {
        | yes e => D.cast e a
        | no _ => 0
      }

    \lemma inc-at-same (D : GradedProduct) {n k : Nat} (a : D.H n) (e : n = k) : inc-at D n a k = D.cast e a
      => unfold inc-at (rewrite (decideEq=_reduce e) idp)

    \lemma inc-at-other (D : GradedProduct) {n k : Nat} (a : D.H n) (ne : n /= k) : inc-at D n a k = 0
      => unfold inc-at (rewrite (decideEq/=_reduce ne) idp)

    \lemma proj-inc (D : GradedProduct) (n : Nat) (a : D.H n) : proj D n (inc D n a) = a
      => inc-at-same D a idp

    \lemma proj-inc-other (D : GradedProduct) {n k : Nat} (ne : n /= k) (a : D.H n) : proj D k (inc D n a) = 0
      => inc-at-other D a ne

    \lemma inc-mul (D : GradedProduct) (p q : Nat) (a : D.H p) (b : D.H q)
      : inc D p a * {DirectSum D} inc D q b = inc D (p Nat.+ q) (D.mul p q a b)
      => sum-ext \lam k => \case decideEq (p Nat.+ q) k \with {
        | yes e => AbMonoid.FinSum-unique {D.H k} {PairsFinSet k} (p, q, e) (\lam s s/= => \case decideEq p s.1 \with {
          | no ne => conv-zero-left D (inc-at D p a) (inc-at D q b) s (inc-at-other D a ne)
          | yes e1 => conv-zero-right D (inc-at D p a) (inc-at D q b) s (inc-at-other D b \lam e2 => s/= (ext (inv e1, inv e2)))
        }) *> D.cast-unique _ e _ *> pmap (D.cast e) (pmap2 (\lam a' b' => D.mul p q a' b') (inc-at-same D a idp) (inc-at-same D b idp))
           *> inv (inc-at-same D _ e)
        | no ne => AbMonoid.FinSum_zro {D.H k} {PairsFinSet k} (\lam s => \case decideEq p s.1 \with {
          | no ne1 => conv-zero-left D (inc-at D p a) (inc-at D q b) s (inc-at-other D a ne1)
          | yes e1 => conv-zero-right D (inc-at D p a) (inc-at D q b) s (inc-at-other D b \lam e2 => ne (pmap2 (Nat.+) e1 e2 *> s.3))
        }) *> inv (inc-at-other D _ ne)
      }

    \lemma decompose (D : GradedProduct) (x : DirectSum D) : ∃ (N : Nat) (x = sum-below {DirectSum D} (\lam n => inc D n (x.1 n)) N)
      => \case x.2 \with {
        | inP (N, z) => inP (N, decompose-at D x z)
      }

    \lemma decompose-at (D : GradedProduct) (x : DirectSum D) {N : Nat} (z : \Pi (n : Nat) -> N <= n -> x.1 n = 0)
      : x = sum-below {DirectSum D} (\lam n => inc D n (x.1 n)) N
      => sum-ext \lam k => inv (sum-below.hom (proj D k) _ N *> component D x.1 z k)
      \where
        \lemma component (D : GradedProduct) (x : \Pi (n : Nat) -> D.H n) {N : Nat} (z : \Pi (n : Nat) -> N <= n -> x n = 0) (k : Nat)
          : sum-below (\lam n => inc-at D n (x n) k) N = x k
          => \case LinearOrder.dec<_<= k N \with {
            | inl k<N => sum-below.unique k<N (\lam n ne => inc-at-other D (x n) ne) *> inc-at-same D (x k) idp
            | inr N<=k => sum-below.zero (\lam n n<N => inc-at-other D (x n) (\lam p => absurd linarith)) *> inv (z k N<=k)
          }

    \func lift (D : GradedProduct) {G : AbGroup} (fs : \Pi (n : Nat) -> AddGroupHom (D.H n) G) : AddGroupHom (DirectSum D) G \cowith
      | func x => (lift-value D fs x).1
      | func-+ {x} {y} => \case x.2, y.2 \with {
        | inP (N, zx), inP (M, zy) =>
          (lift-value D fs ((AddMonoid.+ {DirectSum D}) x y)).2 (N Nat.+ M) (\lam n le => pmap2 (+) (zx n (left-le le)) (zy n (right-le le)) *> zro-left)
          *> pmap (sum-below __ (N Nat.+ M)) (ext \lam n => AddGroupHom.func-+ {fs n})
          *> sum-below.add _ _ (N Nat.+ M)
          *> inv (pmap2 (+) ((lift-value D fs x).2 (N Nat.+ M) (\lam n le => zx n (left-le le)))
                            ((lift-value D fs y).2 (N Nat.+ M) (\lam n le => zy n (right-le le))))
      }
      \where {
        \func Value (D : GradedProduct) {G : AbGroup} (fs : \Pi (n : Nat) -> AddGroupHom (D.H n) G) (x : DirectSum D)
          => \Sigma (g : G) (\Pi (N : Nat) -> (\Pi (n : Nat) -> N <= n -> x.1 n = 0) -> g = sum-below (\lam n => fs n (x.1 n)) N)

        \sfunc lift-value (D : GradedProduct) {G : AbGroup} (fs : \Pi (n : Nat) -> AddGroupHom (D.H n) G) (x : DirectSum D) : Value D fs x
          => \scase x.2 \return Value D fs x \level value-prop D fs x \with {
            | inP (N, z) => (sum-below (\lam n => fs n (x.1 n)) N, \lam M zM => sum-below.bounds (zero-image fs z) (zero-image fs zM))
          }

        \lemma zero-image {D : GradedProduct} {G : AbGroup} (fs : \Pi (n : Nat) -> AddGroupHom (D.H n) G) {x : \Pi (n : Nat) -> D.H n} {N : Nat}
                           (z : \Pi (n : Nat) -> N <= n -> x n = 0) (n : Nat) (le : N <= n) : fs n (x n) = 0
          => pmap (fs n) (z n le) *> AddGroupHom.func-zro {fs n}

        \sfunc value-prop (D : GradedProduct) {G : AbGroup} (fs : \Pi (n : Nat) -> AddGroupHom (D.H n) G) (x : DirectSum D) (a b : Value D fs x) : a = b
          => \case x.2 \with {
            | inP (N, z) => ext (a.2 N z *> inv (b.2 N z))
          }
      }

    \func universal (D : GradedProduct) (G : AbGroup) : QEquiv {AddGroupHom (DirectSum D) G} {\Pi (n : Nat) -> AddGroupHom (D.H n) G} \cowith
      | f h n => h AddGroupHom.∘ inc D n
      | ret => lift D
      | ret_f h => exts \lam x => \case x.2 \with {
        | inP (N, z) => (lift.lift-value D (\lam n => h AddGroupHom.∘ inc D n) x).2 N z *> inv (sum-below.hom h _ N) *> pmap h (inv (decompose-at D x z))
      }
      | f_sec fs => ext \lam n => exts \lam a =>
          (lift.lift-value D fs (inc D n a)).2 (suc n) (\lam k le => inc-at-other D a (\lam p => absurd linarith))
          *> sum-below.unique id<suc (\lam k ne => pmap (fs k) (inc-at-other D a (\lam p => ne (inv p))) *> AddGroupHom.func-zro {fs k})
          *> pmap (fs n) (inc-at-same D a idp)

    \func ringMap {D D' : GradedProduct} (phi : \Pi (n : Nat) -> AddGroupHom (D.H n) (D'.H n))
                  (phi-mul : \Pi (p q : Nat) (a : D.H p) (b : D.H q) -> phi (p Nat.+ q) (D.mul p q a b) = D'.mul p q (phi p a) (phi q b))
                  (phi-one : phi 0 D.one = D'.one) : RingHom (DirectSum D) (DirectSum D') \cowith
      | func x => (\lam n => phi n (x.1 n), \case x.2 \with {
        | inP (N, z) => inP (N, \lam n le => pmap (phi n) (z n le) *> AddGroupHom.func-zro {phi n})
      })
      | func-+ => sum-ext \lam n => AddGroupHom.func-+ {phi n}
      | func-ide => sum-ext (unit-map phi phi-one)
      | func-* {x} {y} => sum-ext \lam n => AddMonoidHom.func-FinSum (phi n) {PairsFinSet n}
          *> AbMonoid.FinSum-ext {D'.H n} {PairsFinSet n} (\lam s => cast-map phi s.3 _ *> pmap (D'.cast s.3) (phi-mul s.1 s.2 (x.1 s.1) (y.1 s.2)))
      \where {
        \lemma unit-map {D D' : GradedProduct} (phi : \Pi (n : Nat) -> AddGroupHom (D.H n) (D'.H n)) (phi-one : phi 0 D.one = D'.one) (n : Nat)
          : phi n (unit D n) = unit D' n \elim n
          | 0 => phi-one
          | suc n => AddGroupHom.func-zro {phi (suc n)}

        \lemma cast-map {D D' : GradedProduct} (phi : \Pi (n : Nat) -> AddGroupHom (D.H n) (D'.H n)) {n m : Nat} (e : n = m) (a : D.H n)
          : phi m (D.cast e a) = D'.cast e (phi n a) \elim m, e
          | _, idp => idp

        \lemma inc-map {D D' : GradedProduct} (phi : \Pi (n : Nat) -> AddGroupHom (D.H n) (D'.H n))
                       (phi-mul : \Pi (p q : Nat) (a : D.H p) (b : D.H q) -> phi (p Nat.+ q) (D.mul p q a b) = D'.mul p q (phi p a) (phi q b))
                       (phi-one : phi 0 D.one = D'.one) (n : Nat) (a : D.H n)
          : ringMap phi phi-mul phi-one (inc D n a) = inc D' n (phi n a)
          => sum-ext {D'} {ringMap phi phi-mul phi-one (inc D n a)} {inc D' n (phi n a)} \lam k => \case decideEq n k \with {
            | yes e => pmap (phi k) (inc-at-same D a e) *> cast-map phi e a *> inv (inc-at-same D' (phi n a) e)
            | no ne => pmap (phi k) (inc-at-other D a ne) *> AddGroupHom.func-zro {phi k} *> inv (inc-at-other D' (phi n a) ne)
          }
      }

    \func sum-ext {D : GradedProduct} {x y : \Sigma (x : \Pi (n : Nat) -> D.H n) (∃ (N : Nat) (\Pi (n : Nat) -> N <= n -> x n = 0))}
                  (h : \Pi (n : Nat) -> x.1 n = y.1 n) : x = y
      => ext (ext h)

    \lemma left-le {N M n : Nat} (le : N Nat.+ M <= n) : N <= n
      => linarith

    \lemma right-le {N M n : Nat} (le : N Nat.+ M <= n) : M <= n
      => linarith

    \lemma support-le {N M n i j : Nat} (le : N Nat.+ M <= n) (e : i Nat.+ j = n) (i<N : i < N) : M <= j
      => linarith

    \func unit (D : GradedProduct) (n : Nat) : D.H n \elim n
      | 0 => D.one
      | suc _ => 0

    \lemma unit-suc (D : GradedProduct) {n : Nat} (n/=0 : n /= 0) : unit D n = 0 \elim n
      | 0 => absurd (n/=0 idp)
      | suc _ => idp

    \func conv (D : GradedProduct) (x y : \Pi (n : Nat) -> D.H n) (n : Nat) : D.H n
      => AbMonoid.FinSum {D.H n} {PairsFinSet n} \lam s => D.cast s.3 (D.mul s.1 s.2 (x s.1) (y s.2))

    \lemma conv-zero-left (D : GradedProduct) (x y : \Pi (n : Nat) -> D.H n) {n : Nat} (s : PairsFinSet n) (h : x s.1 = 0)
      : D.cast s.3 (D.mul s.1 s.2 (x s.1) (y s.2)) = 0
      => pmap (\lam a => D.cast s.3 (D.mul s.1 s.2 a (y s.2))) h *> pmap (D.cast s.3) (Pairing.zro-left (D.mul s.1 s.2)) *> AddGroupHom.func-zro {D.cast s.3}

    \lemma conv-zero-right (D : GradedProduct) (x y : \Pi (n : Nat) -> D.H n) {n : Nat} (s : PairsFinSet n) (h : y s.2 = 0)
      : D.cast s.3 (D.mul s.1 s.2 (x s.1) (y s.2)) = 0
      => pmap (\lam b => D.cast s.3 (D.mul s.1 s.2 (x s.1) b)) h *> pmap (D.cast s.3) (Pairing.zro-right (D.mul s.1 s.2)) *> AddGroupHom.func-zro {D.cast s.3}

    \lemma conv-assoc (D : GradedProduct) (x y z : \Pi (n : Nat) -> D.H n) (n : Nat) : conv D (conv D x y) z n = conv D x (conv D y z) n
      => AbMonoid.FinSum-ext {D.H n} {PairsFinSet n} (\lam s => pmap (D.cast s.3) (AddMonoidHom.func-FinSum (Pairing.right (D.mul s.1 s.2) (z s.2)) {PairsFinSet s.1})
                                                *> AddMonoidHom.func-FinSum (D.cast s.3))
         *> AbMonoid.FinSum-double-dep' (\lam (s : PairsFinSet n) => PairsFinSet s.1)
         *> AbMonoid.FinSum_Equiv2 {D.H n} {SigmaFin (PairsFinSet n) (\lam s => PairsFinSet s.1)} {SigmaFin (PairsFinSet n) (\lam s => PairsFinSet s.2)}
              (FSeriesRing.pairs-assoc n) (\lam a => \case \elim a \with {
                | ((i,j,e1),(k,m,e2)) => term D x y z _ _ _ _
              })
         *> inv (AbMonoid.FinSum-double-dep' (\lam (s : PairsFinSet n) => PairsFinSet s.2))
         *> inv (AbMonoid.FinSum-ext {D.H n} {PairsFinSet n} (\lam s => pmap (D.cast s.3) (AddMonoidHom.func-FinSum (Pairing.left (D.mul s.1 s.2) (x s.1)) {PairsFinSet s.2})
                                                     *> AddMonoidHom.func-FinSum (D.cast s.3)))
      \where
        \lemma term (D : GradedProduct) (x y z : \Pi (n : Nat) -> D.H n) {n i j k m : Nat} (e1 : i Nat.+ j = n) (e2 : k Nat.+ m = i)
                    (e3 : k Nat.+ (m Nat.+ j) = n) (e4 : m Nat.+ j = m Nat.+ j)
          : D.cast e1 (D.mul i j (D.cast e2 (D.mul k m (x k) (y m))) (z j))
            = D.cast e3 (D.mul k (m Nat.+ j) (x k) (D.cast e4 (D.mul m j (y m) (z j))))
          => pmap (D.cast e1) (D.cast-left e2 j _ _) *> D.cast-comp _ _ _
             *> pmap (D.cast (pmap (Nat.`+ j) e2 *> e1)) (D.mul-assoc k m j _ _ _) *> D.cast-comp _ _ _ *> D.cast-unique _ e3 _
             *> pmap (\lam c => D.cast e3 (D.mul k (m Nat.+ j) (x k) c)) (D.cast-unique idp e4 _)
  }
