\import Algebra.Group
\import Algebra.Monoid
\import Algebra.Monoid.Product
\import Algebra.Pointed
\import Paths
\import Paths.Meta

\instance ProductGroup (G H : Group) : Group
  | Monoid => ProductMonoid G H
  | inverse p => (inverse p.1, inverse p.2)
  | inverse-left => pmap2 (__,__) inverse-left inverse-left
  | inverse-right => pmap2 (__,__) inverse-right inverse-right

\instance ProductAddGroup (A B : AddGroup) : AddGroup
  | AddMonoid => ProductAddMonoid A B
  | negative p => (negative p.1, negative p.2)
  | negative-left => pmap2 (__,__) negative-left negative-left
  | negative-right => pmap2 (__,__) negative-right negative-right

\instance ProductCGroup (G H : CGroup) : CGroup
  | Group => ProductGroup G H
  | CMonoid => ProductCMonoid G H

\instance ProductAbGroup (A B : AbGroup) : AbGroup
  | AddGroup => ProductAddGroup A B
  | AbMonoid => ProductAbMonoid A B

\instance TrivialAbGroup : AbGroup (\Sigma)
  | zro => ()
  | + _ _ => ()
  | zro-left => idp
  | +-assoc => idp
  | negative _ => ()
  | negative-left => idp
  | +-comm => idp

-- | Functions into an abelian group, with pointwise operations.
\instance FuncAbGroup (J : \Type) (A : AbGroup) : AbGroup (J -> A)
  | zro _ => zro
  | + f g j => f j + g j
  | zro-left => ext \lam _ => zro-left
  | +-assoc => ext \lam _ => +-assoc
  | negative f j => negative (f j)
  | negative-left => ext \lam _ => negative-left
  | +-comm => ext \lam _ => +-comm