\import Algebra.Group
\import Algebra.Group.GroupCat
\import Algebra.Group.GroupHom
\import Algebra.Monoid
\import Algebra.Monoid.Product
\import Algebra.Pointed
\import Category (Iso)
\import Equiv
\import Paths
\import Paths.Meta

\instance ProductGroup (G H : Group) : Group
  | Monoid => ProductMonoid G H
  | inverse p => (inverse p.1, inverse p.2)
  | inverse-left => pmap2 (__,__) inverse-left inverse-left
  | inverse-right => pmap2 (__,__) inverse-right inverse-right

\instance ProductAddGroup (A B : AddGroup) : AddGroup
  | AddMonoid => ProductAddMonoid A B
  | negative p => (negative p.1, negative p.2)
  | negative-left => pmap2 (__,__) negative-left negative-left
  | negative-right => pmap2 (__,__) negative-right negative-right

\instance ProductCGroup (G H : CGroup) : CGroup
  | Group => ProductGroup G H
  | CMonoid => ProductCMonoid G H

\instance ProductAbGroup (A B : AbGroup) : AbGroup
  | AddGroup => ProductAddGroup A B
  | AbMonoid => ProductAbMonoid A B

\instance TrivialAbGroup : AbGroup (\Sigma)
  | zro => ()
  | + _ _ => ()
  | zro-left => idp
  | +-assoc => idp
  | negative _ => ()
  | negative-left => idp
  | +-comm => idp
  \where {
    \func toTrivial (G : AbGroup) : AddGroupHom G TrivialAbGroup \cowith
      | func _ => ()
      | func-+ => idp

    \func trivialIso.{u} (G : AbGroup.{u}) (h : \Pi (x : G) -> x = 0) : Iso {AbGroupCat.{u}} (toTrivial G) \cowith
      | hinv => \new AddGroupHom {
        | func _ => 0
        | func-+ => inv zro-left
      }
      | hinv_f => exts \lam x => inv (h x)
      | f_hinv => idp
  }

\func copairHom {A B C : AbGroup} (f : AddGroupHom A C) (g : AddGroupHom B C) : AddGroupHom (ProductAbGroup A B) C \cowith
  | func p => f p.1 + g p.2
  | func-+ => pmap2 (+) f.func-+ g.func-+ *> interchange
  \where
    \lemma interchange {C : AbGroup} {a b c d : C} : (a + b) + (c + d) = (a + c) + (b + d)
      => +-assoc *> pmap (a +) (inv +-assoc *> pmap (`+ d) +-comm *> +-assoc) *> inv +-assoc

\instance PiAbGroup {J : \Type} (A : J -> AbGroup) : AbGroup (\Pi (j : J) -> A j)
  | zro _ => zro
  | + f g j => f j + g j
  | zro-left => ext \lam _ => zro-left
  | +-assoc => ext \lam _ => +-assoc
  | negative f j => negative (f j)
  | negative-left => ext \lam _ => negative-left
  | +-comm => ext \lam _ => +-comm
  \where
    \func tuple {J : \Type} {B : AbGroup} {A : J -> AbGroup} (f : \Pi (j : J) -> AddGroupHom B (A j)) : AddGroupHom B (PiAbGroup A) \cowith
      | func b j => f j b
      | func-+ => ext \lam j => (f j).func-+

\instance FuncAbGroup (J : \Type) (A : AbGroup) : AbGroup (J -> A)
  => PiAbGroup (\lam _ => A)
  \where {
    \func precomp {J' J : \Type} (A : AbGroup) (s : J' -> J) : AddGroupHom (FuncAbGroup J A) (FuncAbGroup J' A) \cowith
      | func h j => h (s j)
      | func-+ => idp

    \func precompIso.{u} {J' J : \Type u} (A : AbGroup.{u}) (e : QEquiv {J'} {J}) : Iso {AbGroupCat.{u}} (precomp A e) \cowith
      | hinv => precomp A e.ret
      | hinv_f => exts \lam h => ext \lam j => pmap h (e.f_sec j)
      | f_hinv => exts \lam k => ext \lam j => pmap k (e.ret_f j)
  }