-- | The HoTT book, Section 8.10, in ordinary degree indexing; after ``theorems/homotopy/EilenbergMacLane.agda`` in HoTT-Agda.

\import Algebra.Group
\import Algebra.Pointed (ide)
\import Homotopy.Connectivity
\import Homotopy.HLevel
\import Homotopy.K1.Basic
\import Homotopy.Pointed \hiding (base)
\import Homotopy.Suspension
\import Homotopy.Truncation
\import Logic
\import Order.Biordered
\import Arith.Nat

\func K.{u} (G : CGroup.{u}) (n : Nat) : Pointed.{u} \elim n
  | 0 => Pointed.make (ide {G})
  | 1 => K1Pointed G
  | suc (suc n) => Pointed.make {Trunc_-1+ (suc (suc (suc n))) (Susp (K G (suc n)))} (inT north)

\lemma K-level.{u} {G : CGroup.{u}} (n : Nat) : K G n ofHLevel_-1+ suc n \elim n
  | 0 => \lam _ _ => toProp (\lam _ _ => prop-pi)
  | 1 => K1-level
  | suc (suc n) => isTruncated {Trunc_-1+.level (suc (suc (suc n))) (Susp (K G (suc n)))}

\lemma K-connected.{u} {G : CGroup.{u}} (r : Nat) : isNConnectedType (suc r) (K G (suc r)) \elim r
  | 0 => K1-connected
  | suc r => nconnected-trunc (<=-less id<suc) (susp-nconnected {suc r} (K-connected r))
