{- | ``n``-truncation as a localization: ``LType {truncUniverse n}`` reduces to {Trunc_-1+} and {lEta} to {inT}.
     The framework of modalities is developed in the following paper.
     Egbert Rijke, Michael Shulman, Bas Spitters, Modalities in Homotopy Type Theory, https://arxiv.org/pdf/1706.07526
 -}

\import Equiv
\import Homotopy.HLevel
\import Homotopy.Localization.Modality
\import Homotopy.Localization.Universe
\import Homotopy.Truncation
\import Logic
\import Paths

\instance truncTypes.{u} (n : Nat) : Universe.{u}
  | isLocal A => A ofHLevel_-1+ n

\func trunc-unique.{u} {n : Nat} {A : \Type} (Z : Truncated_-1+.{u} n) (g h : Trunc_-1+ n A -> Z)
                       (p : \Pi (a : A) -> g (inT a) = h (inT a)) (x : Trunc_-1+ n A) : g x = h x
  => Trunc_-1+.elim (\lam x => \new Truncated_-1+ n (g x = h x) (HLevel_-1_suc Z.isTruncated (g x) (h x))) p x

\func truncUniverse.{u} (n : Nat) : Modality.{u} \cowith
  | Universe => truncTypes n
  | localization A => \new Localization {
    | S' => \new Local (Trunc_-1+ n A) (isTruncated {Trunc_-1+.level n A})
    | inL => inT
    | local-univ Z => inP \new QEquiv {
      | ret g => Trunc_-1+.elim (\lam _ => \new Truncated_-1+ n Z Z.local) g
      | ret_f h => path \lam i x => trunc-unique (\new Truncated_-1+ n Z Z.local) _ h (\lam _ => idp) x i
      | f_sec _ => idp
    }
  }
  | isModality A B => \new Local (\Sigma (a : A) (B a)) (HLevels-sigma (\lam a => B a) A.local (\lam a => (B a).local))
