\import Algebra.Group
\import Algebra.Group.GroupCat
\import Algebra.Group.GroupHom
\import Algebra.Group.Product
\import Algebra.Group.SubGroup
\import Algebra.Pointed (zro)
\import Arith.Nat
\import Category (Iso, oIso)
\import Equiv
\import Equiv.Sigma (unit-func)
\import Homotopy.Cohomology
\import Homotopy.Cohomology.Coefficients
\import Homotopy.Connectivity
\import Homotopy.EilenbergMacLane.Algebra
\import Homotopy.EilenbergMacLane.Definition
\import Homotopy.Pointed (->*, Pointed, UnitPointed, base)
\import Logic
\import Paths
\import Paths.Meta
\import Set

\func degreeZero.{u} (X : \Type u) (A : AbGroup.{u}) : Iso {AbGroupCat} (toFunctions X A)
  => AbGroupCat.isoOfEquiv (toFunctions X A) (\new QEquiv {
    | ret h => in0 (\lam x => h (in0 x))
    | ret_f c => \case \elim c \with {
      | in0 _ => idp
    }
    | f_sec _ => ext \lam t => \case \elim t \with {
      | in0 _ => idp
    }
  })
  \where {
    \func toFunctions-map.{u} {X : \Type u} {A : AbGroup.{u}} (c : CoHom 0 X A) (t : Trunc0 X) : A \elim c, t
      | in0 f, in0 x => f x

    \func toFunctions.{u} (X : \Type u) (A : AbGroup.{u}) : AddGroupHom (CoHom 0 X A) (FuncAbGroup (Trunc0 X) A) \cowith
      | func => toFunctions-map
      | func-+ {c} {d} => \case \elim c, \elim d \with {
        | in0 f, in0 g => ext \lam t => \case \elim t \with {
          | in0 x => K-add.degree-zero (f x) (g x)
        }
      }

    \lemma natural.{u} {X : \Type u} {A B : AbGroup.{u}} (f : AddGroupHom A B) (c : CoHom 0 X A)
      : toFunctions-map (mapCoef 0 X f c) = (\lam t => f (toFunctions-map c t)) \elim c
      | in0 _ => ext \lam t => \case \elim t \with {
        | in0 _ => idp
      }
  }

\func degreeZero-fin.{u} {X : \Type u} {m : Nat} (e : QEquiv {X} {Fin m}) (A : AbGroup.{u})
  : Iso {AbGroupCat} {CoHom 0 X A} {FuncAbGroup (Fin m) A} _
  => oIso (degreeZero X A) (FuncAbGroup.precompIso A (symQEquiv (transQEquiv (Trunc0.mapEquiv e) Trunc0.setEquiv)))

\func redDegreeZero.{u} (X : Pointed.{u}) (A : AbGroup.{u}) : Iso {AbGroupCat} (toFunctions X A)
  => AbGroupCat.isoOfEquiv (toFunctions X A) (\new QEquiv {
    | ret h => in0 (\lam x => h.1 (in0 x), h.2)
    | ret_f c => \case \elim c \with {
      | in0 _ => idp
    }
    | f_sec _ => ext (ext \lam t => \case \elim t \with {
      | in0 _ => idp
    })
  })
  \where {
    \func evalBase.{u} (X : Pointed.{u}) (A : AbGroup.{u}) : AddGroupHom (FuncAbGroup (Trunc0 X) A) A \cowith
      | func h => h (in0 base)
      | func-+ => idp

    \func toFunctions-map.{u} {X : Pointed.{u}} {A : AbGroup.{u}} (c : RedCoHom 0 X A)
      : IAbGroup (KernelAddGroup (evalBase X A)) \elim c
      | in0 f => (degreeZero.toFunctions-map (in0 f.1), f.2)

    \func toFunctions.{u} (X : Pointed.{u}) (A : AbGroup.{u})
      : AddGroupHom (RedCoHom 0 X A) (IAbGroup (KernelAddGroup (evalBase X A))) \cowith
      | func => toFunctions-map
      | func-+ {c} {d} => \case \elim c, \elim d \with {
        | in0 f, in0 g => ext (ext \lam t => \case \elim t \with {
          | in0 x => K-add.degree-zero (f.1 x) (g.1 x)
        })
      }
  }

\func degreeZero-connected.{u} (X : Pointed.{u}) (c : isNConnectedType 1 X) (A : AbGroup.{u})
  : Iso {AbGroupCat} (constant X A)
  => AbGroupCat.isoOfEquiv (constant X A) (\new QEquiv {
    | ret => evaluate
    | ret_f _ => idp
    | f_sec d => \case \elim d \with {
      | in0 f => pmap in0 (ext \lam x => \case nconnected1-path c base x \with {
        | inP p => pmap f p
      })
    }
  })
  \where {
    \func constant.{u} (X : Pointed.{u}) (A : AbGroup.{u}) : AddGroupHom A (CoHom 0 X A) \cowith
      | func a => in0 (\lam _ => a)
      | func-+ {a} {b} => pmap in0 (ext \lam _ => inv (K-add.degree-zero a b))

    \func evaluate.{u} {X : Pointed.{u}} {A : AbGroup.{u}} (d : CoHom 0 X A) : A \elim d
      | in0 f => f base
  }

\lemma redDegreeZero-connected.{u} (X : Pointed.{u}) (c : isNConnectedType 1 X) (A : AbGroup.{u}) (d : RedCoHom 0 X A)
  : d = zro {RedCoHom 0 X A} \elim d
  | in0 f => pmap in0 (->*.ext {X} {K A 0} {f} { ->*.zero X (K A 0)}
                        (\lam x => \case nconnected1-path c x base \with {
                          | inP p => pmap f.1 p *> f.2
                        }) prop-pi)

\func pointCoHom.{u} (n : Nat) (A : AbGroup.{u}) : QEquiv {CoHom n (\Sigma) A} {Trunc0 (K A n)}
  => Trunc0.mapEquiv (unit-func (K A n))

\lemma pointCoHom-positive.{u} (n : Nat) (A : AbGroup.{u}) (d : CoHom (suc n) (\Sigma) A)
  : d = zro {CoHom (suc n) (\Sigma) A} \elim d
  | in0 a => \case nconnected1-path (nconnected-mono (suc<=suc zero<=_) (K-connected n)) (a ()) base \with {
    | inP p => pmap in0 (ext \lam _ => p)
  }

\lemma redPointCoHom.{u} (n : Nat) (A : AbGroup.{u}) (d : RedCoHom n UnitPointed A)
  : d = zro {RedCoHom n UnitPointed A} \elim d
  | in0 f => pmap in0 (inv (->*.ext {UnitPointed} {K A n} { ->*.zero UnitPointed (K A n)} {f} (\lam _ => inv f.2) (inv_*> f.2)))
