\import Algebra.Group
\import Algebra.Group.GroupCat
\import Algebra.Group.GroupHom
\import Algebra.Group.Product
\import Algebra.Monoid
\import Algebra.Pointed (zro)
\import Category (Iso)
\import Equiv
\import Homotopy.Cohomology
\import Homotopy.Cohomology.Coefficients
\import Homotopy.Cohomology.DegreeZero
\import Homotopy.Cohomology.Functor
\import Homotopy.EilenbergMacLane.Algebra
\import Homotopy.EilenbergMacLane.Definition
\import Homotopy.EilenbergMacLane.Loop
\import Homotopy.Loop
\import Homotopy.Pointed (->*, Pointed, PointedEquiv, base)
\import Homotopy.Pointed.Mapping
\import Paths
\import Paths.Meta
\import Set

\open ->* (∘*)

\func forget.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : AddGroupHom (RedCoHom n X A) (CoHom n X A) \cowith
  | func c => Trunc0.map c (\lam f => f.1)
  | func-+ {c} {d} => \case \elim c, \elim d \with {
    | in0 _, in0 _ => idp
  }

\func evaluate.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : AddGroupHom (CoHom n X A) (CoHom n (\Sigma) A)
  => pullback n (\lam _ => base)

\func constant.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : AddGroupHom (CoHom n (\Sigma) A) (CoHom n X A)
  => pullback n (\lam _ => ())

\func loopNormalize {X W : Pointed} (k : X -> Loop W) : X ->* Loop W
  => (\lam x => k x *> inv (k base), *>_inv (k base))
  \where {
    \func translate {X W : Pointed} (h : X ->* Loop W) (p : Loop W) : loopNormalize (\lam x => h.1 x *> p) = h
      => ->*.ext (\lam x => pmap (\lam q => (h.1 x *> p) *> inv (q *> p)) h.2 *> cancel (h.1 x) p) (coh h.2 p)

    \func cancel {A : \Type} {a b : A} (y : a = a) (p : a = b) : (y *> p) *> inv (idp *> p) = y
      => pmap ((y *> p) *>) (pmap inv (idp_*> p)) *> *>-assoc y p (inv p) *> pmap (y *>) (*>_inv p)

    \func coh {A : \Type} {a b : A} {q : a = a} (c : q = idp) (p : a = b)
      : (pmap (\lam q' => (q *> p) *> inv (q' *> p)) c *> cancel q p) *> c = *>_inv (q *> p) \elim c
      | idp => idp_*> _ *> cancel-idp p

    \func cancel-idp {A : \Type} {a b : A} (p : a = b) : cancel idp p = *>_inv (idp *> p) \elim p
      | idp => idp
  }

\func normalize.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (f : Cocycle n X A) : RedCocycle n X A
  => (PointedEquiv.inverse (K-loopEquiv n)).map ∘* loopNormalize (\lam x => (K-loopUnit n).1 (f x))
  \where {
    \func formula.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (f : Cocycle n X A) (x : X)
      : (normalize f).1 x = K-add n (f x) (K-neg n (f base))
      => pmap (K-loopInv n).1 (pmap (_ *>) (inv (deloopNeg.map (K-loopEquiv n) (f base))))

    \func translate.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (g : RedCocycle n X A) (a : K A n)
      : normalize (\lam x => K-add n (g.1 x) a) = g
      => IsEquiv.isInj (Map*.postEquiv X (K-loopEquiv {AbGroup.toCGroup A} n)).map-isEquiv
          (->*.compose-assoc (K-loopUnit n) (K-loopInv n) (loopNormalize (\lam x => (K-loopUnit n).1 (K-add n (g.1 x) a)))
           *> pmap (`∘* loopNormalize (\lam x => (K-loopUnit n).1 (K-add n (g.1 x) a))) (PointedEquiv.inverse-sec (K-loopEquiv n))
           *> pmap loopNormalize (funPath \lam x => deloopAdd.map (K-loopEquiv n) (g.1 x) a)
           *> loopNormalize.translate (K-loopUnit n ∘* g) ((K-loopUnit n).1 a))

    \func add-base.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (f : Cocycle n X A) (x : X)
      : K-add n ((normalize f).1 x) (f base) = f x
      => QEquiv.isInj {PointedEquiv.toHAEquiv (K-loopEquiv n)}
          (deloopAdd.map (K-loopEquiv n) _ (f base)
           *> pmap (`*> _) (K-loopInv.right n _) *> *>-assoc _ _ _ *> pmap (_ *>) (inv_*> _))
  }

\func splitIso.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : Iso {AbGroupCat} (join n X A)
  => AbGroupCat.isoOfEquiv (join n X A) (\new QEquiv {
    | ret => split-map
    | ret_f p => split-join p.1 p.2
    | f_sec => join-split
  })
  \where {
    \func join.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u})
      : AddGroupHom (ProductAbGroup (RedCoHom n X A) (CoHom n (\Sigma) A)) (CoHom n X A)
      => copairHom (forget n X A) (constant n X A)

    \func split-map.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (c : CoHom n X A)
      : \Sigma (RedCoHom n X A) (CoHom n (\Sigma) A)
      => (Trunc0.map c normalize, evaluate n X A c)

    \func split.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u})
      : AddGroupHom (CoHom n X A) (ProductAbGroup (RedCoHom n X A) (CoHom n (\Sigma) A))
      => Iso.hinv {splitIso n X A}

    \lemma split-join.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (c : RedCoHom n X A) (d : CoHom n (\Sigma) A)
      : split-map (join n X A (c, d)) = (c, d) \elim c, d
      | in0 g, in0 a => ext (pmap in0 (normalize.translate g (a ())),
                             pmap in0 (ext \lam u => pmap (K-add n __ (a u)) g.2 *> deloopAdd.zro-left (K-loopEquiv n) (a u)))

    \lemma join-split.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (c : CoHom n X A)
      : join n X A (split-map c) = c \elim c
      | in0 f => pmap in0 (ext (normalize.add-base f))

    \lemma join-zero.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (c : RedCoHom n X A)
      : join n X A (c, zro {CoHom n (\Sigma) A}) = forget n X A c
      => pmap2 (AddMonoid.+ {CoHom n X A}) idp (AddGroupHom.func-zro {constant n X A}) *> AddMonoid.zro-right {CoHom n X A}

    \lemma split-forget.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (c : RedCoHom n X A)
      : (split-map (forget n X A c)).1 = c
      => pmap (\lam e => (split-map e).1) (inv (join-zero c)) *> pmap __.1 (split-join c (zro {CoHom n (\Sigma) A}))

    \lemma join-pullback.{u} {n : Nat} {X Y : Pointed.{u}} {A : AbGroup.{u}} (s : X ->* Y)
                              (c : RedCoHom n Y A) (d : CoHom n (\Sigma) A)
      : pullback n s.1 (join n Y A (c, d)) = join n X A (redPullback n s c, d) \elim c, d
      | in0 _, in0 _ => idp

    \lemma join-coefficients.{u} {n : Nat} {X : Pointed.{u}} {A B : AbGroup.{u}} (f : AddGroupHom A B)
                                  (c : RedCoHom n X A) (d : CoHom n (\Sigma) A)
      : mapCoef n X f (join n X A (c, d)) = join n X B (redMapCoef n X f c, mapCoef n (\Sigma) f d) \elim c, d
      | in0 g, in0 a => pmap in0 (ext \lam x => K-add.natural n (AddGroupHom.toGroupHom f) (g.1 x) (a ()))
  }

\func forgetIso.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : Iso {AbGroupCat} (forget (suc n) X A)
  => AbGroupCat.isoOfEquiv (forget (suc n) X A) (\new QEquiv {
    | ret e => (splitIso.split-map e).1
    | ret_f => splitIso.split-forget
    | f_sec e => inv (splitIso.join-zero _)
                 *> pmap (\lam d => splitIso.join (suc n) X A (_, d)) (inv (pointCoHom-positive n A _))
                 *> splitIso.join-split e
  })
