\import Algebra.Group
\import Algebra.Group.GroupCat
\import Algebra.Group.GroupHom
\import Algebra.Group.Transfer
\import Algebra.Monoid
\import Category (Iso)
\import Equiv
\import Function (IsInj)
\import Homotopy.EilenbergMacLane.Algebra
\import Homotopy.EilenbergMacLane.Definition
\import Homotopy.EilenbergMacLane.Loop
\import Homotopy.HomotopyGroup
\import Homotopy.Loop
\import Homotopy.Pointed
\import Homotopy.Pointed.Mapping
\import Logic.Unique (isSet)
\import Paths
\import Set

\open PointedEquiv (∘~)

\func Cocycle.{u} (n : Nat) (X : \Type u) (A : AbGroup.{u}) : \Type u
  => X -> K A n
  \where {
    \func zero.{u} {n : Nat} {X : \Type u} {A : AbGroup.{u}} : Cocycle n X A
      => \lam _ => base

    \func add.{u} {n : Nat} {X : \Type u} {A : AbGroup.{u}} (f g : Cocycle n X A) : Cocycle n X A
      => \lam x => K-add n (f x) (g x)

    \func neg.{u} {n : Nat} {X : \Type u} {A : AbGroup.{u}} (f : Cocycle n X A) : Cocycle n X A
      => \lam x => K-neg n (f x)

    \func toLoop.{u} (n : Nat) (X : \Type u) (A : AbGroup.{u}) : PointedEquiv (Map X (K A n)) (Loop (Map X (K A (suc n))))
      => mapLoop X (K A (suc n)) ∘~ Map.postEquiv X (K-loopEquiv n)
      \where {
        \func add.{u} {n : Nat} {X : \Type u} {A : AbGroup.{u}} (f g : Cocycle n X A)
          : (toLoop n X A).map.1 (Cocycle.add f g) = (toLoop n X A).map.1 f *> (toLoop n X A).map.1 g
          => pmap funPath (funPath \lam x => deloopAdd.map (K-loopEquiv n) (f x) (g x)) *> funPath.concat _ _

        \func neg.{u} {n : Nat} {X : \Type u} {A : AbGroup.{u}} (f : Cocycle n X A)
          : (toLoop n X A).map.1 (Cocycle.neg f) = inv ((toLoop n X A).map.1 f)
          => pmap funPath (funPath \lam x => deloopNeg.map (K-loopEquiv n) (f x)) *> funPath.inverse _
      }

    \func toDoubleLoop.{u} (n : Nat) (X : \Type u) (A : AbGroup.{u})
      : PointedEquiv (Map X (K A n)) (Loop (Loop (Map X (K A (suc (suc n))))))
      => loopEquiv (toLoop (suc n) X A) ∘~ toLoop n X A
      \where {
        \func add.{u} {n : Nat} {X : \Type u} {A : AbGroup.{u}} (f g : Cocycle n X A)
          : (toDoubleLoop n X A).map.1 (Cocycle.add f g) = (toDoubleLoop n X A).map.1 f *> (toDoubleLoop n X A).map.1 g
          => pmap (Loop-Func (toLoop (suc n) X A).map).1 (toLoop.add f g) *> Loop-Func_*> (toLoop (suc n) X A).map _ _

        \func neg.{u} {n : Nat} {X : \Type u} {A : AbGroup.{u}} (f : Cocycle n X A)
          : (toDoubleLoop n X A).map.1 (Cocycle.neg f) = inv ((toDoubleLoop n X A).map.1 f)
          => pmap (Loop-Func (toLoop (suc n) X A).map).1 (toLoop.neg f) *> Loop-Func_inv (toLoop (suc n) X A).map _
      }
  }

\func RedCocycle.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : \Type u
  => X ->* K A n
  \where {
    \func zero.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} : RedCocycle n X A
      => ->*.zero X (K A n)

    \func add.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (f g : RedCocycle n X A) : RedCocycle n X A
      => deloopAdd* (K-loopEquiv n) f g

    \func neg.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (f : RedCocycle n X A) : RedCocycle n X A
      => deloopNeg* (K-loopEquiv n) f

    \func toLoop.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : PointedEquiv (Map* X (K A n)) (Loop (Map* X (K A (suc n))))
      => mapLoop* X (K A (suc n)) ∘~ Map*.postEquiv X (K-loopEquiv n)
      \where {
        \func add.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (f g : RedCocycle n X A)
          : (toLoop n X A).map.1 (RedCocycle.add f g) = (toLoop n X A).map.1 f *> (toLoop n X A).map.1 g
          => pmap mapLoop*.fromHom (deloopAdd*.post (K-loopEquiv n) f g)
             *> mapLoop*.fromHom-concat {X} {K A (suc n)} (->*.compose {X} {K A n} {Loop (K A (suc n))} (K-loopUnit n) f)
                                        (->*.compose {X} {K A n} {Loop (K A (suc n))} (K-loopUnit n) g)

        \func neg.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (f : RedCocycle n X A)
          : (toLoop n X A).map.1 (RedCocycle.neg f) = inv ((toLoop n X A).map.1 f)
          => pmap mapLoop*.fromHom (deloopNeg*.post (K-loopEquiv n) f)
             *> mapLoop*.fromHom-inv {X} {K A (suc n)} (->*.compose {X} {K A n} {Loop (K A (suc n))} (K-loopUnit n) f)
      }

    \func toDoubleLoop.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u})
      : PointedEquiv (Map* X (K A n)) (Loop (Loop (Map* X (K A (suc (suc n))))))
      => loopEquiv (toLoop (suc n) X A) ∘~ toLoop n X A
      \where {
        \func add.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (f g : RedCocycle n X A)
          : (toDoubleLoop n X A).map.1 (RedCocycle.add f g) = (toDoubleLoop n X A).map.1 f *> (toDoubleLoop n X A).map.1 g
          => pmap (Loop-Func (toLoop (suc n) X A).map).1 (toLoop.add f g) *> Loop-Func_*> (toLoop (suc n) X A).map _ _

        \func neg.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (f : RedCocycle n X A)
          : (toDoubleLoop n X A).map.1 (RedCocycle.neg f) = inv ((toDoubleLoop n X A).map.1 f)
          => pmap (Loop-Func (toLoop (suc n) X A).map).1 (toLoop.neg f) *> Loop-Func_inv (toLoop (suc n) X A).map _
      }
  }

\func CoHom.{u} (n : Nat) (X : \Type u) (A : AbGroup.{u}) : AbGroup.{u}
  => injectiveAbGroup (pi2Target n X A) (toPi2-map n X A) (toPi2-inj n X A)
                      (in0 Cocycle.zero) (Trunc0.map2 __ __ Cocycle.add) (Trunc0.map __ Cocycle.neg)
                      (pmap in0 (Cocycle.toDoubleLoop n X A).map.2) (toPi2-+ n X A) (toPi2-neg n X A)
  \where {
    \func pi2Target.{u} (n : Nat) (X : \Type u) (A : AbGroup.{u}) : AbGroup.{u}
      => AbGroup.fromCGroup (PiCGroup 0 (Map X (K A (suc (suc n)))))

    \func toPi2-map.{u} (n : Nat) (X : \Type u) (A : AbGroup.{u}) (c : Trunc0 (Cocycle n X A)) : pi2Target n X A
      => Trunc0.map c (Cocycle.toDoubleLoop n X A).map.1

    \lemma toPi2-inj.{u} (n : Nat) (X : \Type u) (A : AbGroup.{u}) : IsInj (toPi2-map n X A)
      => IsEquiv.isInj (Trunc0.map-isEquiv (Cocycle.toDoubleLoop n X A).map-isEquiv)

    \lemma toPi2-+.{u} (n : Nat) (X : \Type u) (A : AbGroup.{u}) (c d : Trunc0 (Cocycle n X A))
      : toPi2-map n X A (Trunc0.map2 c d Cocycle.add) = (AddMonoid.+ {pi2Target n X A}) (toPi2-map n X A c) (toPi2-map n X A d) \elim c, d
      | in0 f, in0 g => pmap in0 (Cocycle.toDoubleLoop.add f g)

    \lemma toPi2-neg.{u} (n : Nat) (X : \Type u) (A : AbGroup.{u}) (c : Trunc0 (Cocycle n X A))
      : toPi2-map n X A (Trunc0.map c Cocycle.neg) = (AddGroup.negative {pi2Target n X A}) (toPi2-map n X A c) \elim c
      | in0 f => pmap in0 (Cocycle.toDoubleLoop.neg f)

    \func classOf.{u} {n : Nat} {X : \Type u} {A : AbGroup.{u}} (f : Cocycle n X A) : CoHom n X A
      => in0 f

    \func rec.{u} {n : Nat} {X : \Type u} {A : AbGroup.{u}} {B : \Type} (p : isSet B) (f : Cocycle n X A -> B) (c : CoHom n X A) : B
      => Trunc0.rec p c f

    \lemma rec-eval.{u} {n : Nat} {X : \Type u} {A : AbGroup.{u}} {B : \Type} {p : isSet B} {f : Cocycle n X A -> B} {g : Cocycle n X A}
      : rec p f (classOf g) = f g \level p _ _
      => Trunc0.rec-eval

    \func elim.{u} {n : Nat} {X : \Type u} {A : AbGroup.{u}} {P : CoHom n X A -> \Type}
                   (p : \Pi (c : CoHom n X A) -> isSet (P c)) (f : \Pi (g : Cocycle n X A) -> P (classOf g)) (c : CoHom n X A) : P c
      => Trunc0.elim p c f

    \lemma elim-eval.{u} {n : Nat} {X : \Type u} {A : AbGroup.{u}} {P : CoHom n X A -> \Type}
                         {p : \Pi (c : CoHom n X A) -> isSet (P c)} {f : \Pi (g : Cocycle n X A) -> P (classOf g)} {g : Cocycle n X A}
      : elim p f (classOf g) = f g \level p _ _ _
      => Trunc0.elim-eval

    \func toPi2.{u} (n : Nat) (X : \Type u) (A : AbGroup.{u}) : AddGroupHom (CoHom n X A) (pi2Target n X A) \cowith
      | func => toPi2-map n X A
      | func-+ => toPi2-+ n X A _ _

    \func pi2Iso.{u} (n : Nat) (X : \Type u) (A : AbGroup.{u}) : Iso {AbGroupCat} (toPi2 n X A)
      => AbGroupCat.isoOfEquiv (toPi2 n X A) (Trunc0.mapEquiv (IsEquiv.toQEquiv (Cocycle.toDoubleLoop n X A).map-isEquiv))
  }

\func RedCoHom.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : AbGroup.{u}
  => injectiveAbGroup (pi2Target n X A) (toPi2-map n X A) (toPi2-inj n X A)
                      (in0 RedCocycle.zero) (Trunc0.map2 __ __ RedCocycle.add) (Trunc0.map __ RedCocycle.neg)
                      (pmap in0 (RedCocycle.toDoubleLoop n X A).map.2) (toPi2-+ n X A) (toPi2-neg n X A)
  \where {
    \func pi2Target.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : AbGroup.{u}
      => AbGroup.fromCGroup (PiCGroup 0 (Map* X (K A (suc (suc n)))))

    \func toPi2-map.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) (c : Trunc0 (RedCocycle n X A)) : pi2Target n X A
      => Trunc0.map c (RedCocycle.toDoubleLoop n X A).map.1

    \lemma toPi2-inj.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : IsInj (toPi2-map n X A)
      => IsEquiv.isInj (Trunc0.map-isEquiv (RedCocycle.toDoubleLoop n X A).map-isEquiv)

    \lemma toPi2-+.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) (c d : Trunc0 (RedCocycle n X A))
      : toPi2-map n X A (Trunc0.map2 c d RedCocycle.add) = (AddMonoid.+ {pi2Target n X A}) (toPi2-map n X A c) (toPi2-map n X A d) \elim c, d
      | in0 f, in0 g => pmap in0 (RedCocycle.toDoubleLoop.add f g)

    \lemma toPi2-neg.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) (c : Trunc0 (RedCocycle n X A))
      : toPi2-map n X A (Trunc0.map c RedCocycle.neg) = (AddGroup.negative {pi2Target n X A}) (toPi2-map n X A c) \elim c
      | in0 f => pmap in0 (RedCocycle.toDoubleLoop.neg f)

    \func classOf.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} (f : RedCocycle n X A) : RedCoHom n X A
      => in0 f

    \func rec.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} {B : \Type} (p : isSet B) (f : RedCocycle n X A -> B) (c : RedCoHom n X A) : B
      => Trunc0.rec p c f

    \lemma rec-eval.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} {B : \Type} {p : isSet B} {f : RedCocycle n X A -> B} {g : RedCocycle n X A}
      : rec p f (classOf g) = f g \level p _ _
      => Trunc0.rec-eval

    \func elim.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} {P : RedCoHom n X A -> \Type}
                   (p : \Pi (c : RedCoHom n X A) -> isSet (P c)) (f : \Pi (g : RedCocycle n X A) -> P (classOf g)) (c : RedCoHom n X A) : P c
      => Trunc0.elim p c f

    \lemma elim-eval.{u} {n : Nat} {X : Pointed.{u}} {A : AbGroup.{u}} {P : RedCoHom n X A -> \Type}
                         {p : \Pi (c : RedCoHom n X A) -> isSet (P c)} {f : \Pi (g : RedCocycle n X A) -> P (classOf g)} {g : RedCocycle n X A}
      : elim p f (classOf g) = f g \level p _ _ _
      => Trunc0.elim-eval

    \func toPi2.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : AddGroupHom (RedCoHom n X A) (pi2Target n X A) \cowith
      | func => toPi2-map n X A
      | func-+ => toPi2-+ n X A _ _

    \func pi2Iso.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : Iso {AbGroupCat} (toPi2 n X A)
      => AbGroupCat.isoOfEquiv (toPi2 n X A) (Trunc0.mapEquiv (IsEquiv.toQEquiv (RedCocycle.toDoubleLoop n X A).map-isEquiv))

    \func toPi1.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u})
      : AddGroupHom (RedCoHom n X A) (AddGroup.fromGroup (PiGroup 0 (Map* X (K A (suc n))))) \cowith
      | func c => Trunc0.map c (RedCocycle.toLoop n X A).map.1
      | func-+ {c} {d} => \case \elim c, \elim d \with {
        | in0 f, in0 g => pmap in0 (RedCocycle.toLoop.add f g)
      }

    \lemma toPi1-inj.{u} (n : Nat) (X : Pointed.{u}) (A : AbGroup.{u}) : IsInj (toPi1 n X A)
      => IsEquiv.isInj (Trunc0.map-isEquiv (RedCocycle.toLoop n X A).map-isEquiv)
  }
