\import Algebra.Group
\import Algebra.Group.Aut
\import Algebra.Group.GroupCat
\import Algebra.Group.GroupHom
\import Algebra.Group.Product
\import Category \hiding (id, o, .o)
\import Equiv
\import Equiv.Univalence
\import Homotopy.EckmannHilton
\import Homotopy.Loop
\import Homotopy.Pointed
\import Homotopy.Space
\import Homotopy.Sphere
\import Logic
\import Paths
\import Set \hiding (#, .#)

\func pi.{u} (n : Nat) (X : Pointed.{u}) => Trunc0 (Omega^ n X)

\func piMap.{u} (n : Nat) {X Y : Pointed.{u}} (f : X ->* Y) (t : pi n X) : pi n Y
  => Trunc0.map t (Omega^-Func n f).1

\lemma piMap-isEquiv.{u} (n : Nat) {X Y : Pointed.{u}} (f : X ->* Y) (e : IsEquiv f.1) : IsEquiv (piMap n f)
  => Trunc0.map-isEquiv (Omega^-Func.isEquiv n f e)

\lemma piMap-id.{u} (n : Nat) {X : Pointed.{u}} (t : pi n X) : piMap n (->*.id {X}) t = t
  => pmap (Trunc0.map t) (pmap __.1 (Omega^-Func.id n {X})) *> Trunc0.map-id t

\lemma piMap-comp.{u} (n : Nat) {X Y Z : Pointed.{u}} (g : Y ->* Z) (f : X ->* Y) (t : pi n X)
  : piMap n (g ->*.∘* f) t = piMap n g (piMap n f t)
  => pmap (Trunc0.map t) (pmap __.1 (Omega^-Func.comp n g f))
     *> inv (Trunc0.map-comp t (Omega^-Func n f).1 (Omega^-Func n g).1)

\func piSphereEquiv.{u} (n : Nat) (X : Pointed.{u}) : QEquiv {Trunc0 (Sphere.pointed n ->* X)} {pi n X}
  => Trunc0.mapEquiv (Equiv.toQEquiv (=_Equiv (omegaSphere n X)))

\instance PiGroup.{u} (n : Nat) (X : Pointed.{u}) : Group (Trunc0 (Omega^ (suc n) X))
  => Aut (base {Omega^ n X})

\instance PiCGroup.{u} (n : Nat) (X : Pointed.{u}) : CGroup (Trunc0 (Omega^ (suc (suc n)) X))
  | Group => PiGroup (suc n) X
  | *-comm {x} {y} => \case \elim x, \elim y \with {
    | in0 p, in0 q => pmap in0 (Omega^2-Commutative.Commutative {\new Omega^2-Commutative (Omega^ n X)} p q)
  }

\func piGroupMap.{u} (n : Nat) {X Y : Pointed.{u}} (f : X ->* Y) : GroupHom (PiGroup n X) (PiGroup n Y) \cowith
  | func => piMap (suc n) f
  | func-* {x} {y} => \case \elim x, \elim y \with {
    | in0 p, in0 q => pmap in0 (Loop-Func_*> (Omega^-Func n f) p q)
  }

\func PiGroup_Product.{u} (n : Nat) (X Y : Pointed.{u})
  : PiGroup n (PointedProduct X Y) = {Group.{u}} ProductGroup (PiGroup n X) (PiGroup n Y)
  => Cat.isotoid (iso n X Y)
  \where {
    \func equiv.{u} (n : Nat) (X Y : Pointed.{u}) : QEquiv {pi n (PointedProduct X Y)} {\Sigma (pi n X) (pi n Y)}
      => transQEquiv (Trunc0.mapEquiv (IsEquiv.toQEquiv (omegaProductMap.isEquiv n X Y))) Trunc0.productEquiv

    \func map.{u} (n : Nat) {X Y : Pointed.{u}} (z : pi n (PointedProduct X Y)) : \Sigma (pi n X) (pi n Y)
      => (piMap n {PointedProduct X Y} {X} PointedProduct.proj1 z, piMap n {PointedProduct X Y} {Y} PointedProduct.proj2 z)

    \lemma map=equiv.{u} (n : Nat) {X Y : Pointed.{u}} (z : pi n (PointedProduct X Y)) : map n z = equiv n X Y z \elim z
      | in0 w => pmap2 (\lam u v => ((in0 u, in0 v) : \Sigma (pi n X) (pi n Y)))
                       (inv (path \lam i => (pmap __.1 (omegaProductMap.proj1 n X Y) @ i) w))
                       (inv (path \lam i => (pmap __.1 (omegaProductMap.proj2 n X Y) @ i) w))

    \lemma map-isEquiv.{u} (n : Nat) {X Y : Pointed.{u}} : IsEquiv (map n {X} {Y})
      => transport IsEquiv (inv (path \lam i z => map=equiv n z @ i)) (inP (equiv n X Y))

    \func hom.{u} (n : Nat) (X Y : Pointed.{u})
      : GroupHom (PiGroup n (PointedProduct X Y)) (ProductGroup (PiGroup n X) (PiGroup n Y)) \cowith
      | func => map (suc n)
      | func-* => pmap2 (__,__) (piGroupMap n {PointedProduct X Y} {X} PointedProduct.proj1).func-*
                                (piGroupMap n {PointedProduct X Y} {Y} PointedProduct.proj2).func-*

    \func iso.{u} (n : Nat) (X Y : Pointed.{u}) : Iso {GroupCat} (hom n X Y)
      => GroupCat.isoOfEquiv (hom n X Y) (IsEquiv.toQEquiv (map-isEquiv (suc n)))
  }

\func PiGroup_LoopShift.{u} (n : Nat) (X : Pointed.{u}) : PiGroup n (Loop X) = {Group.{u}} PiGroup (suc n) X
  => pmap (\lam (P : Pointed.{u}) => (Aut (base {P}) : Group.{u})) (omegaLoopShift n X)
  \where
    \func equiv.{u} (n : Nat) (X : Pointed.{u}) : QEquiv {pi n (Loop X)} {pi (suc n) X}
      => Trunc0.mapEquiv (Equiv.toQEquiv (=_Equiv (pmap (BaseSpace.E {__}) (omegaLoopShift n X))))

\func PiGroup_basepoint.{u} (n : Nat) {X : \Type u} {x y : X} (p : x = y)
  : PiGroup n (Pointed.make x) = {Group.{u}} PiGroup n (Pointed.make y)
  => Cat.isotoid (iso n p)
  \where {
    \func map {X : \Type} {x y : X} (p : x = y) : Pointed.make x ->* Pointed.make y
      => (\lam z => z, p)

    \func act.{u} (n : Nat) {X : \Type u} {x y : X} (p : x = y) (t : pi n (Pointed.make x)) : pi n (Pointed.make y)
      => piMap n (map p) t

    \lemma act-id.{u} (n : Nat) {X : \Type u} {x : X} (t : pi n (Pointed.make x)) : act n idp t = t
      => piMap-id n t

    \lemma act-comp.{u} (n : Nat) {X : \Type u} {x y z : X} (p : x = y) (q : y = z) (t : pi n (Pointed.make x))
      : act n (p *> q) t = act n q (act n p t)
      => piMap-comp n (map q) (map p) t

    -- | Basepoint change in dimension one is conjugation.
    \lemma act-1.{u} {X : \Type u} {x y : X} (p : x = y) (q : x = x) : act 1 p (in0 q) = in0 (inv p *> q *> p)
      => idp

    \func equiv.{u} (n : Nat) {X : \Type u} {x y : X} (p : x = y)
      : QEquiv {pi n (Pointed.make x)} {pi n (Pointed.make y)}
      => IsEquiv.toQEquiv (piMap-isEquiv n (map p) (inP idEquiv))

    \func hom.{u} (n : Nat) {X : \Type u} {x y : X} (p : x = y)
      : GroupHom (PiGroup n (Pointed.make x)) (PiGroup n (Pointed.make y))
      => piGroupMap n (map p)

    \func iso.{u} (n : Nat) {X : \Type u} {x y : X} (p : x = y) : Iso {GroupCat} (hom n p)
      => GroupCat.isoOfEquiv (hom n p) (IsEquiv.toQEquiv (piMap-isEquiv (suc n) (map p) (inP idEquiv)))
  }
